### ISSUE TITLE
macOS Segmentation fault

### ISSUE THREAD

**Issue by grylem** [jarmuszz/per#1]
Hi
per -s 0755
Segmentation fault: 11
per -S 0755
user: 
group: 
other: 
special: 
0000
Segmentation fault: 11

Regards

**Comment by jarmuszz** [comment]
Hello,
Sorry for late response.
Sadly, I don't have an environment in which I could debug macOS build but I will try to look into that :)
Regards

**Comment by grylem** [comment]
Thanks.
now works fine.
Maybe you can add also symbolic notation like 0755 = go+rx,u+rwx ?
Regards.

**Comment by jarmuszz** [comment]
Hello,
I will probably add this notation someday but I lack time currently.
Thanks for opening this issue and for the suggestion.
Best regards.
