### ISSUE TITLE
macOS : Race condition cought

### ISSUE THREAD

**Issue by grylem** [jarmuszz/per#2]
Hi
./per -v per.1
per: Race condition cought, file per.1 modified.: Invalid argument

Also please add #elif defined(__unix__) || defined (__APPLE__) to per.h
Regards.

manpage in mdoc format
[per.1.gz](https://github.com/jarmuszz/per/files/6506991/per.1.gz)

**Comment by jarmuszz** [comment]
Hello,
Once again thanks for the bug report.
I did changes in the last commit e6eee9e that could possibly fix this race condition error.
Great thanks for the manpage in mdoc format, it is way better than mine, it is now merged.
I also added #elif defined(unix) || defined (APPLE) to per.h.
Best regards.

**Comment by grylem** [comment]
Hi

> I also added #elif defined(unix) || defined (APPLE) to per.h.

I don't know why github fixed string it works for me
`#elif defined(__unix__) || defined(__APPLE__)`

Regards.

**Comment by jarmuszz** [comment]
Hello,
Just pushed `defined(__APPLE__)`.
Regards

**Comment by grylem** [comment]
Thanks everything is fine now
Regards.
